# メトリックの再送最大回数。本番では60
max_retry: 60
# バッファサイズ。本番では360
buffersize: 360
# 実行期間。開始、終了の「日付T時間」
during: ['2023-07-26T03:33', '2023-07-26T15:50']
# 障害タイミング。発生・終了の時刻を配列で指定する
accidents: [['2023-07-26T03:34', '2023-07-26T13:45']]
# 正常postを無視したいなら以下にtrue
quiet: null
